#!/bin/bash

BACKUP_PATH=.
BACKUP_DIR=./backup_dir
EXTENTIONS=''
ARCHIVE_PATH=./backup.tar
HELP=1

OPTIONS=$(getopt -o h,p:,d:,o: --long help,path:,dir:,output: -- "$@")
[[ $? -eq 0 ]] || {
	exit 1
}

eval set -- "$OPTIONS"

while [[ "$1" != "--" ]]; do
	case "$1" in
		"-h" | "--help" )
			HELP=0
			shift
			;;
		"-p" |  "--path" )
			BACKUP_PATH="$2"
			shift; shift
			;;
		"-d" |  "--dir" )
			BACKUP_DIR="$2"
			shift; shift
			;;
		"-o" |  "--output" )
			ARCHIVE_PATH="$2"
			shift; shift
			;;
	esac
done

shift

EXTENTIONS=( "$@" )

#echo BACKUP_PATH=$BACKUP_PATH
#echo BACKUP_DIR=$BACKUP_DIR
#echo ARCHIVE_PATH=$ARCHIVE_PATH

if [[ $HELP -eq 0 ]]; then
	echo help	# TODO
	exit 0
fi

TEST_COMMAND=("-true")

#echo ${#TEST_COMMAND[*]}

if [[ ${#EXTENTIONS[*]} -ne 0 ]]; then
	TEST_COMMAND=("-false")
	for EXT in "${EXTENTIONS[@]}"; do
		TEST_COMMAND=(${TEST_COMMAND[*]} -o -iname "'*.$EXT'")
	done
fi

TEST_COMMAND=(-type f "'('" ${TEST_COMMAND[*]} "')'" )

echo ${TEST_COMMAND[*]}
#TEST_COMMAND=(-type f)
#echo ${#TEST_COMMAND[*]}
( cd $BACKUP_PATH && eval "find ${TEST_COMMAND[*]} -print" )
